### ISSUE TITLE
Need example with details about wbuchwalter/tf-mnist:gpu

### ISSUE THREAD

**Issue by cheyang** [Azure/kubeflow-labs#41]
In [tfjob introduction](https://github.com/Azure/kubeflow-labs/tree/master/6-tfjob#exercise-1-a-simple-tfjob) , it mentions  wbuchwalter/tf-mnist:gpu. Can you please provide details about how to build this docker image? Thanks.

**Comment by ritazh** [comment]
The source for the image is here: https://github.com/Azure/kubeflow-labs/blob/master/1-docker/src/

You can follow https://github.com/Azure/kubeflow-labs/tree/master/1-docker#building-the-image to build and push the image yourself.

**Comment by cheyang** [comment]
Is it for GPU？ Looks like it's for docker image only with CPU support.
